aliasvault/aliasvault

- docker-compose.yml
> Update docker-compose.yml to include database volume for SmtpService

- src/AliasVault.Api/Controllers/FaviconController.cs
…ion instead of warning (#383)
> Log failed favicon extraction as information instead of warning

- install.sh
> Always download latest docker compose files on install or update

- src/Databases/AliasServerDb/UserEmailClaim.cs
> chore: update UserEmailClaim.cs

- src/AliasVault.Admin/Main/Layout/TopMenu.razor
- src/AliasVault.Admin/wwwroot/css/tailwind.css
- src/AliasVault.Client/Main/Layout/TopMenu.razor
- src/AliasVault.Client/wwwroot/css/tailwind.css
Please include a summary of the changes and the related issue(s).
Fixes #553 
Minor layout tweak
> Update mobile menu position in client and admin

- .github/workflows/dotnet-e2e-admin-tests.yml
- .github/workflows/dotnet-e2e-misc-tests.yml
Fixes deprecated GitHub Action commands.
Link to any issues that this PR addresses:
Fixes #569
> Bump upload-artifact to v4

- src/AliasVault.Api/Controllers/AuthController.cs
- src/AliasVault.Client/Main/Pages/Settings/Security/Components/DeleteAccountSection.razor
- src/AliasVault.Client/Main/Pages/Settings/Security/Components/RecentAuthLogsSection.razor
- src/AliasVault.Client/Main/Pages/Settings/Security/DeleteAccount.razor
- src/AliasVault.Client/Main/Pages/Settings/Security/Security.razor
- src/Shared/AliasVault.RazorComponents/Alerts/AlertMessageError.razor
- src/Shared/AliasVault.RazorComponents/Alerts/AlertMessageInfo.razor
- src/Shared/AliasVault.RazorComponents/Alerts/AlertMessageSuccess.razor
- src/Shared/AliasVault.RazorComponents/Alerts/AlertMessageWarning.razor
- src/Shared/AliasVault.RazorComponents/Alerts/MessageWarning.razor
- src/Shared/AliasVault.Shared/Models/Enums/AuthEventType.cs
- src/Shared/AliasVault.Shared/Models/WebApi/Auth/DeleteAccountRequest.cs
- src/Tests/AliasVault.E2ETests/Tests/Client/Shard4/AuthTests.cs
> Add user delete account option to client app

- src/AliasVault.Admin/Main/Pages/Settings/Server.razor
- src/AliasVault.Client/Main/Components/Email/RecentEmails.razor
- src/AliasVault.Client/Main/Components/Widgets/CreateNewIdentityWidget.razor
- src/AliasVault.Client/Main/Pages/Credentials/Delete.razor
Fixes #579
Contains some additional fixes on top of #579 as well.
> Admin and client UI tweaks

- browser-extensions/chrome/src/app/components/Layout/Header.tsx
- browser-extensions/chrome/src/app/pages/EmailsList.tsx
- browser-extensions/chrome/src/app/pages/Login.tsx
- browser-extensions/chrome/src/shared/SqliteClient.tsx
- browser-extensions/chrome/src/shared/WebApiService.ts
Please include a summary of the changes and the related issue(s).
Fixes #612
> Chrome extension throws error when credential has no email

- browser-extensions/chrome/src/shared/WebApiService.ts
Please include a summary of the changes and the related issue(s).
Fixes #618
> Add client header to webapi token refresh call

- browser-extensions/chrome/src/contentScript/Popup.ts
- browser-extensions/chrome/src/shared/__tests__/AppInfo.test.ts
- docs/misc/release/create-new-release.md
- src/AliasVault.Api/Controllers/VaultController.cs
- src/AliasVault.Client/Main/Layout/DbStatusIndicator.razor
- src/AliasVault.Client/Main/Pages/Sync/StatusMessages/Creating.razor
- src/AliasVault.Client/Main/Pages/Sync/StatusMessages/Merging.razor
- src/AliasVault.Client/Main/Pages/Sync/StatusMessages/PendingMigrations.razor
- src/AliasVault.Client/Services/Database/DbService.cs
- src/AliasVault.Client/wwwroot/css/tailwind.css
- src/Tests/AliasVault.E2ETests/Common/BrowserExtensionPlaywrightTest.cs
- src/Tests/AliasVault.E2ETests/Tests/Client/Shard2/DbUpgradeTests.cs
- src/Tests/AliasVault.E2ETests/Tests/Extensions/ChromeExtensionTests.cs
- src/Tests/AliasVault.E2ETests/Tests/Extensions/VaultOutdatedTests.cs
> Add E2E tests for browser extension credential create flow

- browser-extensions/chrome/src/app/components/Layout/BottomNav.tsx
- browser-extensions/chrome/src/app/components/Layout/Header.tsx
- browser-extensions/chrome/src/app/pages/AuthSettings.tsx
- browser-extensions/chrome/src/app/pages/Settings.tsx
Please include a summary of the changes and the related issue(s).
Fixes #647
> Show browser extension version on settings page

- browser-extensions/chrome/src/contentScript/Popup.ts
> Add favicon extract resize and compression

- docs/contact/index.md
- docs/index.md
- docs/installation/advanced/manual-setup.md
- docs/installation/install.md
- docs/installation/troubleshooting.md
> Add troubleshooting guide to docs

- src/AliasVault.Admin/Main/Pages/Dashboard/Components/EmailClaimsCard.razor
- src/AliasVault.Admin/Main/Pages/Dashboard/Components/RegistrationStatisticsCard.razor
- src/AliasVault.Admin/Main/Pages/Dashboard/Components/ReturningUsersCard.razor
- src/AliasVault.Admin/Main/Pages/Dashboard/Index.razor
- src/AliasVault.Admin/Main/Pages/Emails.razor
- src/AliasVault.Admin/Main/Pages/Logging/Auth.razor
- src/AliasVault.Admin/Main/Pages/Logging/General.razor
- src/AliasVault.Admin/Main/Pages/Users/Users.razor
- src/AliasVault.Admin/wwwroot/css/tailwind.css
> Add more stats to admin dashboard

- src/AliasVault.Api/Controllers/VaultController.cs
> Store less vault revisions to reduce history filesize

- docs/installation/install.md
- docs/misc/dev/index.md
- docs/misc/private-vs-public-email.md
> Add private vs public email domain documentation (#673)

- browser-extension/src/entrypoints/content.ts
- browser-extension/src/entrypoints/contentScript/Form.ts
- browser-extension/src/entrypoints/contentScript/Popup.ts
- browser-extension/src/entrypoints/contentScript/Shared.ts
- browser-extension/src/entrypoints/contentScript/style.css
> Use shadowroot for browser extension content script to prevent CSS style conflicts

- browser-extension/src/utils/formDetector/FormFiller.ts
- browser-extension/src/utils/formDetector/__tests__/FormFiller.generic.test.ts
> Improve password autofill mechanism by simulating user typing behavior

- browser-extension/src/entrypoints/background.ts
- browser-extension/src/entrypoints/background/VaultMessageHandler.ts
- browser-extension/src/entrypoints/content.ts
- browser-extension/src/entrypoints/contentScript/Form.ts
- browser-extension/src/entrypoints/contentScript/Popup.ts
- browser-extension/src/entrypoints/contentScript/style.css
- browser-extension/src/entrypoints/popup/context/AuthContext.tsx
- browser-extension/src/entrypoints/popup/pages/AuthSettings.tsx
- browser-extension/src/entrypoints/popup/pages/Settings.tsx
- browser-extension/src/entrypoints/popup/pages/Unlock.tsx
> Show autofill popup dismiss button when vault is locked

- browser-extension/src/entrypoints/contentScript/Popup.ts
> Improve create credential popup page title extraction

- README.md
- browser-extension/safari-xcode/AliasVault/AliasVault.xcodeproj/project.pbxproj
- browser-extension/src/utils/AppInfo.ts
- browser-extension/wxt.config.ts
- docs/misc/release/create-new-release.md
- src/Shared/AliasVault.Shared.Core/AppInfo.cs
> Bump version to 0.14.0

- .github/workflows/docker-compose-build.yml
- .github/workflows/docker-compose-pull.yml
- docs/installation/troubleshooting.md
- install.sh
> Cleanup and simplify install.sh

- .gitignore
- .vscode/launch.json
- .vscode/tasks.json
- src/AliasVault.Admin/AliasVault.Admin.csproj
- src/AliasVault.Admin/Main/Models/UserViewModel.cs
- src/AliasVault.Admin/Main/Pages/Emails.razor
- src/AliasVault.Admin/Main/Pages/Logging/Auth.razor
- src/AliasVault.Admin/Main/Pages/Logging/General.razor
- src/AliasVault.Admin/Main/Pages/Users/Users.razor
- src/AliasVault.Admin/package-lock.json
> Improve admin listings and search behaviour

- src/AliasVault.Admin/Main/Models/UserEmailClaimWithCount.cs
- src/AliasVault.Admin/Main/Pages/Dashboard/Components/EmailClaimsCard.razor
- src/AliasVault.Admin/Main/Pages/Emails.razor
- src/AliasVault.Admin/Main/Pages/Users/View/Components/EmailClaimTable.razor
- src/AliasVault.Admin/Main/Pages/Users/View/Index.razor
- src/AliasVault.Admin/wwwroot/css/tailwind.css
- src/AliasVault.Api/Controllers/VaultController.cs
- src/Databases/AliasServerDb/Migrations/PostgresqlMigrations/20250320101427_AddEmailClaimDisabledFlag.Designer.cs
- src/Databases/AliasServerDb/Migrations/PostgresqlMigrations/20250320101427_AddEmailClaimDisabledFlag.cs
- src/Databases/AliasServerDb/Migrations/SqliteMigrations/20250320101616_AddEmailClaimDisabledFlag.Designer.cs
- src/Databases/AliasServerDb/Migrations/SqliteMigrations/20250320101616_AddEmailClaimDisabledFlag.cs
- src/Databases/AliasServerDb/Migrations/SqliteMigrations/AliasServerDbContextSqliteModelSnapshot.cs
- src/Databases/AliasServerDb/UserEmailClaim.cs
- src/Services/AliasVault.SmtpService/Handlers/DatabaseMessageStore.cs
- src/Tests/AliasVault.E2ETests/Tests/Client/Shard1/EmailDecryptionTests.cs
- src/Tests/AliasVault.IntegrationTests/SmtpServer/SmtpServerTests.cs
> Add option to disable email claims which rejects incoming emails

- browser-extension/src/entrypoints/background/VaultMessageHandler.ts
- browser-extension/src/entrypoints/contentScript/Form.ts
- browser-extension/src/entrypoints/contentScript/Popup.ts
- browser-extension/src/utils/formDetector/FormFiller.ts
- docs/misc/dev/browser-extensions.md
> Browser extension password autofill is not accepted by some websites

- install.sh
> Make install.sh latest version retrieval work with latest MacOS bash

- .env.example
- README.md
- docs/installation/advanced/build-from-source.md
- docs/installation/advanced/database.md
- docs/installation/advanced/manual-setup.md
- docs/installation/install.md
- install.sh
> Update manual install docs

- src/AliasVault.Client/Main/Pages/Settings/ImportExport/Components/ImportServiceCard.razor
- src/AliasVault.Client/Services/CredentialService.cs
- src/Utilities/AliasVault.FaviconExtractor/AliasVault.FaviconExtractor.csproj
- src/Utilities/AliasVault.FaviconExtractor/FaviconExtractor.cs
> Add bulk favicon extract to import wizard

- src/AliasVault.Client/Main/Components/Widgets/SearchWidget.razor
> Improve vault search functionality

- src/AliasVault.Client/Main/Pages/Settings/ImportExport/Components/ImportServiceCard.razor
- src/AliasVault.Client/wwwroot/css/tailwind.css
- src/Utilities/AliasVault.FaviconExtractor/FaviconExtractor.cs
> Add detection of duplicate items to import wizard

- browser-extension/src/entrypoints/contentScript/Filter.ts
- browser-extension/src/entrypoints/popup/pages/CredentialsList.tsx
- browser-extension/src/utils/formDetector/FormDetector.ts
- browser-extension/src/utils/formDetector/FormFiller.ts
- browser-extension/src/utils/formDetector/__tests__/FormDetector.en.test.ts
- browser-extension/src/utils/formDetector/__tests__/FormDetector.generic.test.ts
- browser-extension/src/utils/formDetector/__tests__/FormFiller.generic.test.ts
- browser-extension/src/utils/formDetector/__tests__/test-forms/display-none.html
- browser-extension/src/utils/formDetector/__tests__/test-forms/en-login-form1.html
- browser-extension/src/utils/formDetector/__tests__/test-forms/opacity-zero.html
- browser-extension/src/utils/formDetector/__tests__/test-forms/visibility-hidden.html
This PR improves the form detection and autofill capabilities to work on more diverse login forms.
Fixes #732
> Improve browser extension form detection and autofill

- browser-extension/src/entrypoints/popup/components/Button.tsx
- browser-extension/src/entrypoints/popup/pages/Login.tsx
- browser-extension/src/entrypoints/popup/utils/SrpUtility.tsx
- browser-extension/src/utils/WebApiService.ts
- browser-extension/src/utils/types/errors/ApiAuthError.ts
- browser-extension/src/utils/types/webapi/BadRequestResponse.ts
- src/AliasVault.Admin/Main/Pages/Users/View/Index.razor
> Add proper error messages to browser extension login

- browser-extension/src/entrypoints/background/VaultMessageHandler.ts
- browser-extension/src/entrypoints/contentScript/Form.ts
- browser-extension/src/entrypoints/contentScript/Popup.ts
- browser-extension/src/entrypoints/contentScript/style.css
- browser-extension/src/entrypoints/popup/pages/CredentialDetails.tsx
- browser-extension/src/entrypoints/popup/pages/CredentialsList.tsx
- browser-extension/src/utils/SqliteClient.tsx
- browser-extension/src/utils/formDetector/FieldPatterns.ts
- browser-extension/src/utils/formDetector/FormDetector.ts
- browser-extension/src/utils/formDetector/FormFiller.ts
- browser-extension/src/utils/formDetector/__tests__/FormDetector.nl.test.ts
- browser-extension/src/utils/formDetector/__tests__/FormFiller.generic.test.ts
- browser-extension/src/utils/formDetector/__tests__/TestUtils.ts
- browser-extension/src/utils/formDetector/__tests__/test-forms/en-login-form1.html
- browser-extension/src/utils/formDetector/__tests__/test-forms/nl-registration-form10.html
- browser-extension/src/utils/types/Credential.ts
- src/Databases/AliasClientDb/AliasClientDbContext.cs
- src/Utilities/AliasVault.FaviconExtractor/FaviconExtractor.cs
> Add manual user/pass create option to browser extension new alias popup

- src/AliasVault.Client/Main/Components/Widgets/SearchWidget.razor
- src/AliasVault.Client/Main/Pages/Credentials/AddEdit.razor
- src/AliasVault.Client/Main/Pages/Credentials/Delete.razor
- src/AliasVault.Client/Main/Pages/Credentials/View.razor
- src/Tests/AliasVault.E2ETests/Common/ClientPlaywrightTest.cs
- src/Tests/AliasVault.E2ETests/Tests/Client/Shard1/CredentialTests.cs
- src/Tests/AliasVault.E2ETests/Tests/Client/Shard2/DbSyncTests.cs
- src/Tests/AliasVault.E2ETests/Tests/Client/Shard5/AttachmentTests.cs
- src/Tests/AliasVault.E2ETests/Tests/Client/Shard5/TotpTests.cs
> Main aliasvault client UI and ux tweaks

- browser-extension/src/entrypoints/background.ts
- browser-extension/src/entrypoints/background/VaultMessageHandler.ts
- browser-extension/src/entrypoints/contentScript/Popup.ts
- browser-extension/src/utils/SqliteClient.tsx
- browser-extension/src/utils/types/messaging/DefaultEmailDomainResponse.ts
- browser-extension/src/utils/types/messaging/StringResponse.ts
> Make browser extension identity generator language setting aware

- src/AliasVault.Client/Main/Pages/Settings/ImportExport/Components/ImportServiceProtonPass.razor
- src/AliasVault.Client/Main/Pages/Settings/ImportExport/ImportExport.razor
- src/AliasVault.Client/wwwroot/img/importers/protonpass.svg
- src/Tests/AliasVault.UnitTests/AliasVault.UnitTests.csproj
- src/Tests/AliasVault.UnitTests/TestData/Exports/protonpass.csv
- src/Tests/AliasVault.UnitTests/Utilities/ImportExportTests.cs
- src/Utilities/AliasVault.ImportExport/Importers/ProtonPassImporter.cs
- src/Utilities/AliasVault.ImportExport/Models/Imports/ProtonPassCsvRecord.cs
> Add Proton Pass importer

- src/AliasVault.Client/Auth/Pages/Unlock.razor
> Update webauthn unlock animation margin

- browser-extension/src/entrypoints/content.ts
- browser-extension/src/entrypoints/contentScript/Form.ts
- browser-extension/src/entrypoints/contentScript/Popup.ts
- browser-extension/src/entrypoints/contentScript/style.css
- docs/misc/dev/browser-extensions.md
- src/AliasVault.Admin/Auth/Pages/Login.razor
- src/AliasVault.Client/Auth/Pages/Login.razor
- src/AliasVault.Client/Auth/Pages/Register.razor
> Browser extension make autofill work with more input element variations

- browser-extension/src/entrypoints/contentScript/Popup.ts
- browser-extension/src/entrypoints/contentScript/style.css
- browser-extension/src/utils/formDetector/FieldPatterns.ts
- browser-extension/src/utils/formDetector/FormDetector.ts
- browser-extension/src/utils/formDetector/__tests__/FormDetector.serviceName.en.test.ts
- browser-extension/src/utils/formDetector/__tests__/FormDetector.serviceName.nl.test.ts
- browser-extension/src/utils/formDetector/__tests__/TestUtils.ts
- docs/misc/dev/browser-extensions.md
> Browser extension make service name extraction more accurate

- src/AliasVault.Client/Auth/Pages/Login.razor
- src/AliasVault.Client/Main/Pages/Settings/Security/ChangePassword.razor
> Changing password twice in a row without reloading page throws error

- src/AliasVault.Client/Main/Components/Email/RecentEmails.razor
> Change date format in emails component on credentials page to be shorter

- browser-extension/safari-xcode/AliasVault/AliasVault.xcodeproj/project.pbxproj
- browser-extension/src/utils/AppInfo.ts
- browser-extension/wxt.config.ts
- src/Shared/AliasVault.Shared.Core/AppInfo.cs
> Bump version to 0.16.2 (#818)

- apps/browser-extension/src/entrypoints/background.ts
- apps/browser-extension/src/entrypoints/background/ContextMenu.ts
- apps/browser-extension/src/entrypoints/background/PopupMessageHandler.ts
- apps/browser-extension/src/entrypoints/content.ts
- apps/browser-extension/src/entrypoints/contentScript/Popup.ts
- apps/browser-extension/src/entrypoints/contentScript/style.css
- apps/browser-extension/src/entrypoints/popup/context/AuthContext.tsx
- apps/browser-extension/src/entrypoints/popup/pages/AuthSettings.tsx
- apps/browser-extension/src/entrypoints/popup/pages/Settings.tsx
- apps/browser-extension/src/entrypoints/popup/pages/Unlock.tsx
- apps/browser-extension/src/utils/Constants.ts
> Add extra enable/disable setting toggles to browser extension

- apps/browser-extension/src/entrypoints/contentScript/Popup.ts
> Browser extension autofill popup search/filter does not work correctly

- apps/mobile-app/utils/SqliteClient.tsx
> iOS app changing password for existing credential sometimes does not get saved

- docker-compose.yml
> Restore docker-compose.yml container versions to :latest

- apps/server/Tests/AliasVault.UnitTests/TestData/Exports/bitwarden.csv
- apps/server/Tests/AliasVault.UnitTests/Utilities/ImportExportTests.cs
- apps/server/Utilities/AliasVault.ImportExport/Importers/BaseImporter.cs
> Vault import fails if one or more 2FA tokens cannot be parsed

- apps/browser-extension/package-lock.json
- apps/browser-extension/package.json
- apps/browser-extension/src/entrypoints/popup/pages/AuthSettings.tsx
> Browser extension using a self-hosted URL with no https prefix causes a crash

- apps/server/AliasVault.Client/wwwroot/css/tailwind.css
- apps/server/Shared/AliasVault.Shared.Core/MobileApps/Constants.cs
> Add Android app download links to client

- apps/server/AliasVault.Admin/Main/Pages/Users/View/Components/RefreshTokenTable.razor
- apps/server/AliasVault.Admin/Main/Pages/Users/View/Index.razor
> Add "revoke all" option to admin page to revoke all active user sessions

- apps/server/AliasVault.Admin/Main/Models/UserViewModel.cs
- apps/server/AliasVault.Admin/Main/Pages/Users/Users.razor
- apps/server/AliasVault.Admin/StartupTasks.cs
> Show amount of emails received per user to admin users list

- apps/mobile-app/app/(tabs)/settings/vault-unlock.tsx
- apps/mobile-app/app/login.tsx
- apps/mobile-app/context/AuthContext.tsx
- apps/mobile-app/ios/Autofill/CredentialProviderViewController.swift
> App does not properly check if biometrics are available before asking the user if they want to use it

- apps/browser-extension/src/entrypoints/popup/pages/EmailDetails.tsx
- apps/browser-extension/src/utils/EncryptionUtility.ts
- apps/browser-extension/src/utils/WebApiService.ts
- apps/mobile-app/app/(tabs)/emails/[id].tsx
- apps/mobile-app/utils/EncryptionUtility.tsx
- apps/mobile-app/utils/WebApiService.ts
> Downloading email attachments in browser extension and mobile app doesn't work

- apps/server/AliasVault.Client/Main/Components/Widgets/CreateNewIdentityWidget.razor
- apps/server/AliasVault.Client/Main/Pages/Credentials/AddEdit.razor
- apps/server/AliasVault.Client/Program.cs
- apps/server/AliasVault.Client/Services/QuickCreateStateService.cs
- apps/server/AliasVault.Client/wwwroot/css/tailwind.css
> Tweak credential create flow when switching between random alias and advanced in web app

- apps/server/AliasVault.Admin/Main/Pages/Settings/Server.razor
- apps/server/AliasVault.Api/Controllers/VaultController.cs
- apps/server/Services/AliasVault.TaskRunner/Program.cs
- apps/server/Services/AliasVault.TaskRunner/Tasks/DisabledEmailCleanupTask.cs
- apps/server/Shared/AliasVault.Shared.Server/Models/ServerSettingsModel.cs
- apps/server/Shared/AliasVault.Shared.Server/Services/ServerSettingsService.cs
- apps/server/Tests/AliasVault.E2ETests/Tests/Client/Shard1/EmailDecryptionTests.cs
- apps/server/Tests/AliasVault.IntegrationTests/TaskRunner/SeedData.cs
- apps/server/Tests/AliasVault.IntegrationTests/TaskRunner/TaskRunnerTests.cs
- apps/server/Tests/AliasVault.IntegrationTests/TaskRunner/TestHostBuilder.cs
> Add background task to delete emails for disabled aliases after x days

- apps/server/AliasVault.Admin/Main/App.razor
- apps/server/nginx.conf
> Add x-forwarded-prefix header to admin to support running on non-default ports

- apps/mobile-app/ios/VaultUI/Components/CredentialCardView.swift
- apps/mobile-app/ios/VaultUI/Views/CredentialProviderView.swift
> iOS autofill long press "view details" button doesn't work

- apps/browser-extension/src/assets/tailwind.css
- apps/browser-extension/src/entrypoints/popup/context/NavigationContext.tsx
> Browser extension logging in from autofill popup does not show confirm screen

- apps/server/AliasVault.Client/Main/Pages/Settings/ImportExport/Components/ImportServiceLastPass.razor
- apps/server/AliasVault.Client/Main/Pages/Settings/ImportExport/ImportExport.razor
- apps/server/AliasVault.Client/wwwroot/img/importers/lastpass.svg
- apps/server/Tests/AliasVault.UnitTests/AliasVault.UnitTests.csproj
- apps/server/Tests/AliasVault.UnitTests/TestData/Exports/lastpass.csv
- apps/server/Tests/AliasVault.UnitTests/Utilities/ImportExportTests.cs
- apps/server/Utilities/AliasVault.ImportExport/Importers/LastPassImporter.cs
- apps/server/Utilities/AliasVault.ImportExport/Models/Imports/LastPassCsvRecord.cs
> Add LastPass credential importer

- .gitignore
- apps/server/AliasVault.Admin/Main/Pages/Logging/Auth.razor
- apps/server/AliasVault.Admin/Main/Pages/Users/View/Components/AuthLogTable.razor
- apps/server/AliasVault.Admin/Main/Pages/Users/View/Components/EmailClaimTable.razor
- apps/server/AliasVault.Admin/Main/Pages/Users/View/Index.razor
- apps/server/AliasVault.Admin/wwwroot/css/tailwind.css
> Make username clickable in admin auth log page to go to user detail page

- apps/browser-extension/src/entrypoints/popup/App.tsx
- apps/browser-extension/src/entrypoints/popup/components/Icons/HeaderIcons.tsx
- apps/browser-extension/src/entrypoints/popup/components/Layout/Header.tsx
- apps/browser-extension/src/entrypoints/popup/index.html
- apps/browser-extension/src/entrypoints/popup/pages/CredentialDetails.tsx
- apps/browser-extension/src/entrypoints/popup/pages/CredentialsList.tsx
- apps/browser-extension/src/entrypoints/popup/pages/EmailDetails.tsx
- apps/browser-extension/src/entrypoints/popup/pages/EmailsList.tsx
- apps/browser-extension/src/entrypoints/popup/pages/Login.tsx
- apps/browser-extension/src/entrypoints/popup/pages/Settings.tsx
- apps/browser-extension/src/entrypoints/popup/pages/Unlock.tsx
- apps/browser-extension/src/entrypoints/popup/utils/PopoutUtility.ts
> Add popout button to browser extension on login and index pages

- apps/server/AliasVault.Admin/Main/Models/ServerStatistics.cs
- apps/server/AliasVault.Admin/Main/Models/TopIpAddress.cs
- apps/server/AliasVault.Admin/Main/Models/TopUserByAliases.cs
- apps/server/AliasVault.Admin/Main/Models/TopUserByStorage.cs
- apps/server/AliasVault.Admin/Main/Pages/Dashboard/AllTimeStats.razor
- apps/server/AliasVault.Admin/Main/Pages/Dashboard/Index.razor
- apps/server/AliasVault.Admin/Main/Pages/Logging/Auth.razor
- apps/server/AliasVault.Admin/Program.cs
- apps/server/AliasVault.Admin/Services/StatisticsService.cs
- apps/server/AliasVault.Admin/wwwroot/css/tailwind.css
> Add all-time stats page to admin (#967)

- .vscode/tasks.json
- apps/server/AliasVault.Client/Main/Components/Email/EmailPreview.razor
- apps/server/AliasVault.Client/Main/Components/Email/EmailPreviewSkeleton.razor
- apps/server/AliasVault.Client/Main/Components/Email/EmailRow.razor
- apps/server/AliasVault.Client/Main/Components/Email/EmailRowSkeleton.razor
- apps/server/AliasVault.Client/Main/Pages/Emails/Home.razor
- apps/server/AliasVault.Client/wwwroot/appsettings.json
- apps/server/AliasVault.Client/wwwroot/css/tailwind.css
- apps/server/Shared/AliasVault.RazorComponents/ConfirmModal.razor
- apps/server/Tests/AliasVault.E2ETests/Tests/Client/Shard1/EmailDecryptionTests.cs
Fixes #967
Add any additional context, screenshots, or explanations here.
> Add sidebar to email list page in web app on desktop

- apps/browser-extension/src/entrypoints/background.ts
- apps/browser-extension/src/entrypoints/background/VaultMessageHandler.ts
- apps/browser-extension/src/entrypoints/contentScript/Popup.ts
- apps/browser-extension/src/entrypoints/popup/pages/CredentialAddEdit.tsx
- apps/browser-extension/src/utils/SqliteClient.ts
- apps/browser-extension/src/utils/dist/shared/identity-generator/index.d.ts
- apps/browser-extension/src/utils/dist/shared/identity-generator/index.js
- apps/browser-extension/src/utils/dist/shared/identity-generator/index.mjs
- apps/browser-extension/src/utils/types/messaging/IdentitySettingsResponse.ts
- apps/mobile-app/app/(tabs)/credentials/add-edit.tsx
- apps/mobile-app/utils/SqliteClient.tsx
- apps/mobile-app/utils/dist/shared/identity-generator/index.d.ts
- apps/mobile-app/utils/dist/shared/identity-generator/index.js
- apps/mobile-app/utils/dist/shared/identity-generator/index.mjs
- apps/server/AliasVault.Client/Main/Pages/Settings/General.razor
- apps/server/AliasVault.Client/Main/Pages/Settings/ImportExport/Components/ImportServiceAliasVault.razor
- apps/server/AliasVault.Client/Main/Pages/Settings/ImportExport/ImportExport.razor
- apps/server/AliasVault.Client/Services/CredentialService.cs
- apps/server/AliasVault.Client/Services/JsInterop/JsInteropService.cs
- apps/server/AliasVault.Client/Services/SettingsService.cs
- apps/server/AliasVault.Client/wwwroot/js/dist/shared/identity-generator/index.d.ts
- apps/server/AliasVault.Client/wwwroot/js/dist/shared/identity-generator/index.js
- apps/server/AliasVault.Client/wwwroot/js/dist/shared/identity-generator/index.mjs
- docs/installation/install.md
- install.sh
- shared/identity-generator/package-lock.json
- shared/identity-generator/src/implementations/base/IdentityGenerator.ts
- shared/identity-generator/src/interfaces/IIdentityGenerator.ts
> Add fixed gender setting for alias generation

- apps/server/AliasVault.Client/Main/Components/Email/EmailPreview.razor
- apps/server/AliasVault.Client/Main/Components/Email/EmailRow.razor
- apps/server/AliasVault.Client/Main/Pages/Emails/Home.razor
- apps/server/AliasVault.Client/Main/Pages/Settings/General.razor
- apps/server/AliasVault.Client/wwwroot/css/tailwind.css
> Make emails page in web client auto refresh

- apps/browser-extension/package.json
- apps/browser-extension/safari-xcode/AliasVault/AliasVault.xcodeproj/project.pbxproj
- apps/browser-extension/src/utils/AppInfo.ts
- apps/browser-extension/src/utils/WebApiService.ts
- apps/browser-extension/wxt.config.ts
- apps/mobile-app/android/app/build.gradle
- apps/mobile-app/app.json
- apps/mobile-app/ios/AliasVault.xcodeproj/project.pbxproj
- apps/mobile-app/utils/AppInfo.ts
- apps/server/Shared/AliasVault.Shared.Core/AppInfo.cs
- fastlane/metadata/browser-extension/en-US/changelogs/0.20.1.txt
> Browser extension cannot login to aliasvault.net after fresh install

- apps/server/AliasVault.Client/Auth/Pages/Unlock.razor
- apps/server/AliasVault.Client/Main/Pages/Settings/ImportExport/Components/ResetVaultSection.razor
- apps/server/AliasVault.Client/Main/Pages/Settings/ImportExport/ImportExport.razor
- apps/server/AliasVault.Client/Main/Pages/Settings/ImportExport/ResetVault.razor
- apps/server/AliasVault.Client/Resources/Components/Main/Pages/Settings/ImportExport/ResetVault.en.resx
- apps/server/AliasVault.Client/Resources/Components/Main/Settings/ImportExport/ResetVaultSection.en.resx
- apps/server/AliasVault.Client/Resources/Pages/Main/Settings/ImportExport/ImportExport.en.resx
- apps/server/AliasVault.Client/Services/CredentialService.cs
- apps/server/Tests/AliasVault.E2ETests/Common/ClientPlaywrightTest.cs
- apps/server/Tests/AliasVault.E2ETests/Tests/Client/Shard5/ResetVaultTests.cs
> Add reset vault option to delete all credentials in web app

- apps/server/AliasVault.Admin/wwwroot/css/tailwind.css
- apps/server/AliasVault.Client/wwwroot/css/tailwind.css
- apps/server/Shared/AliasVault.RazorComponents/ConfirmModal.razor
> Fix admin "restore vault" button

- apps/server/AliasVault.Admin/Main/Pages/Account/ManageLayout.razor
- apps/server/AliasVault.Admin/Main/Pages/Dashboard/AllTimeStats.razor
- apps/server/AliasVault.Admin/Main/Pages/Emails.razor
- apps/server/AliasVault.Admin/Main/Pages/Logging/Auth.razor
- apps/server/AliasVault.Admin/Main/Pages/Logging/General.razor
- apps/server/AliasVault.Admin/Main/Pages/Settings/Server.razor
- apps/server/AliasVault.Admin/Main/Pages/Users/Users.razor
- apps/server/Shared/AliasVault.RazorComponents/Headings/Breadcrumb.razor
> Show correct breadcrumbs in admin

- apps/server/AliasVault.Client/Main/Pages/Settings/Security/Components/ShowRecoveryCodes.razor
- apps/server/AliasVault.Client/Main/Pages/Settings/Security/Disable2Fa.razor
- apps/server/AliasVault.Client/Main/Pages/Settings/Security/Enable2Fa.razor
- apps/server/AliasVault.Client/Resources/Components/Main/Pages/Settings/Security/Disable2Fa.en.resx
- apps/server/AliasVault.Client/wwwroot/css/tailwind.css
- apps/server/Shared/AliasVault.RazorComponents/Alerts/AlertMessageError.razor
> Tweak enable/disable 2FA flow in web app and add missing translations

- apps/browser-extension/src/entrypoints/popup/pages/CredentialsList.tsx
- apps/mobile-app/android/app/src/main/java/net/aliasvault/app/autofill/utils/CredentialMatcher.kt
- apps/mobile-app/android/app/src/test/java/net/aliasvault/app/nativevaultmanager/AutofillTest.kt
- apps/mobile-app/app/(tabs)/credentials/index.tsx
- apps/mobile-app/ios/VaultModels/Credential.swift
- apps/mobile-app/ios/VaultUI/Views/CredentialProviderView.swift
- apps/server/AliasVault.Client/Main/Components/Widgets/SearchWidget.razor
- apps/server/AliasVault.Client/wwwroot/css/tailwind.css
> Improve credential filter and search logic to make it smarter across all clients

- apps/server/AliasVault.Admin/Main/Models/RecentUsageAliases.cs
- apps/server/AliasVault.Admin/Main/Models/RecentUsageEmails.cs
- apps/server/AliasVault.Admin/Main/Models/RecentUsageRegistrations.cs
- apps/server/AliasVault.Admin/Main/Models/RecentUsageStatistics.cs
- apps/server/AliasVault.Admin/Main/Models/UserUsageStatistics.cs
- apps/server/AliasVault.Admin/Main/Pages/Dashboard/Index.razor
- apps/server/AliasVault.Admin/Main/Pages/Dashboard/RecentUsage/Components/RecentUsageAliasesTable.razor
- apps/server/AliasVault.Admin/Main/Pages/Dashboard/RecentUsage/Components/RecentUsageEmailsTable.razor
- apps/server/AliasVault.Admin/Main/Pages/Dashboard/RecentUsage/Components/RecentUsageRegistrationsTable.razor
- apps/server/AliasVault.Admin/Main/Pages/Dashboard/RecentUsageStats.razor
- apps/server/AliasVault.Admin/Main/Pages/Users/View/Components/AuthLogTable.razor
- apps/server/AliasVault.Admin/Main/Pages/Users/View/Index.razor
- apps/server/AliasVault.Admin/Services/StatisticsService.cs
- apps/server/AliasVault.Admin/wwwroot/css/tailwind.css
- apps/server/AliasVault.Client/wwwroot/css/tailwind.css
> Add recent activity statistics to admin

- apps/browser-extension/src/utils/SqliteClient.ts
- apps/browser-extension/src/utils/dist/shared/identity-generator/index.d.ts
- apps/mobile-app/app/(tabs)/credentials/[id].tsx
- apps/mobile-app/app/(tabs)/credentials/add-edit.tsx
- apps/mobile-app/components/credentials/details/AttachmentSection.tsx
- apps/mobile-app/components/credentials/details/AttachmentUploader.tsx
- apps/mobile-app/components/credentials/details/FilePreviewModal.tsx
- apps/mobile-app/i18n/locales/en.json
- apps/mobile-app/ios/Podfile.lock
- apps/mobile-app/package-lock.json
- apps/mobile-app/package.json
- apps/mobile-app/utils/SqliteClient.tsx
- apps/mobile-app/utils/dist/shared/identity-generator/index.d.ts
- apps/mobile-app/utils/dist/shared/models/vault/index.d.ts
- apps/server/AliasVault.Client/wwwroot/js/dist/shared/identity-generator/index.d.ts
- shared/identity-generator/src/factories/IdentityGeneratorFactory.ts
> Add credential attachment upload/download feature to mobile app

- apps/browser-extension/src/entrypoints/contentScript/Popup.ts
- apps/browser-extension/src/entrypoints/popup/pages/CredentialAddEdit.tsx
- apps/browser-extension/src/entrypoints/popup/pages/EmailsList.tsx
- apps/browser-extension/src/i18n/locales/en.json
- apps/mobile-app/app/(tabs)/credentials/_layout.tsx
- apps/mobile-app/app/(tabs)/credentials/add-edit.tsx
- apps/mobile-app/app/(tabs)/settings/_layout.tsx
- apps/mobile-app/components/EmailCard.tsx
- apps/mobile-app/hooks/useVaultMutate.ts
- apps/mobile-app/i18n/locales/en.json
- apps/mobile-app/utils/ValidationSchema.ts
- apps/server/AliasVault.Client/Main/Pages/Sync/StatusMessages/Creating.razor
- apps/server/AliasVault.Client/Services/LanguageService.cs
> Misc translation tweaks

- apps/mobile-app/context/AuthContext.tsx
> Prevent app re-initialization during cold boot and unlock/login

- SINGLE-CONTAINER.md
- apps/browser-extension/src/entrypoints/background/VaultMessageHandler.ts
- apps/browser-extension/src/i18n/locales/en.json
- apps/browser-extension/src/utils/WebApiService.ts
- apps/mobile-app/app/login.tsx
- apps/mobile-app/i18n/locales/en.json
- apps/mobile-app/utils/WebApiService.ts
- apps/mobile-app/utils/types/errors/LocalAuthError.ts
> Show more descriptive error in iOS and Android apps when API connection fails for self-hosted users

- apps/server/AliasVault.Admin/Main/Pages/Emails.razor
- apps/server/AliasVault.Admin/Main/Pages/Logging/Auth.razor
- apps/server/AliasVault.Admin/Main/Pages/Logging/General.razor
- apps/server/AliasVault.Admin/Main/Pages/Users/Users.razor
- apps/server/AliasVault.Admin/Program.cs
> Searching in admin lists can cause race condition and return old search results

- apps/server/AliasVault.Admin/Main/Pages/Logging/General.razor
- apps/server/AliasVault.Admin/Main/Pages/Users/Delete.razor
- apps/server/AliasVault.Admin/Main/Pages/Users/View/Index.razor
- apps/server/AliasVault.Admin/wwwroot/css/tailwind.css
- apps/server/Services/AliasVault.SmtpService/Handlers/DatabaseMessageStore.cs
- apps/server/Services/AliasVault.SmtpService/Workers/SmtpServerWorker.cs
- apps/server/Services/AliasVault.TaskRunner/Tasks/EmailCleanupTask.cs
- apps/server/Services/AliasVault.TaskRunner/Tasks/LogCleanupTask.cs
- apps/server/Services/AliasVault.TaskRunner/Workers/TaskRunnerWorker.cs
- apps/server/Tests/AliasVault.E2ETests/Tests/Admin/UserManagementTests.cs
- apps/server/Utilities/AliasVault.Logging/LoggingConfiguration.cs
> Enable logging non-warnings to database log and adjust existing warning levels

- apps/server/AliasVault.Client/Main/Pages/Settings/General.razor
- apps/server/AliasVault.Client/Resources/Pages/Main/Settings/General.en.resx
> Add explanation between private and public email domains to general settings page

- apps/mobile-app/android/app/src/main/java/net/aliasvault/app/nativevaultmanager/NativeVaultManager.kt
- apps/mobile-app/app/(tabs)/settings/_layout.tsx
- apps/mobile-app/app/(tabs)/settings/clipboard-clear.tsx
- apps/mobile-app/app/(tabs)/settings/index.tsx
- apps/mobile-app/app/_layout.tsx
- apps/mobile-app/components/credentials/CredentialCard.tsx
- apps/mobile-app/components/credentials/details/TotpSection.tsx
- apps/mobile-app/components/form/FormInputCopyToClipboard.tsx
- apps/mobile-app/context/AuthContext.tsx
- apps/mobile-app/context/ClipboardCountdownContext.tsx
- apps/mobile-app/i18n/locales/en.json
- apps/mobile-app/ios/NativeVaultManager/RCTNativeVaultManager.mm
- apps/mobile-app/ios/NativeVaultManager/VaultManager.swift
- apps/mobile-app/specs/NativeVaultManager.ts
> Add automatic clipboard clear to mobile apps after copying a value

- apps/server/AliasVault.Client/Auth/Pages/Unlock.razor
- apps/server/AliasVault.Client/wwwroot/css/tailwind.css
> Update user avatar style on unlock page

- apps/server/AliasVault.Admin/Main/Models/ServerStatistics.cs
- apps/server/AliasVault.Admin/Main/Models/TopUserByCredentials.cs
- apps/server/AliasVault.Admin/Main/Pages/Dashboard/AllTimeStats.razor
- apps/server/AliasVault.Admin/Services/StatisticsService.cs
- apps/server/AliasVault.Admin/wwwroot/css/tailwind.css
> Add "top users by credentials" to admin all time stats

- apps/server/AliasVault.Client/Main/Pages/Credentials/Delete.razor
- apps/server/Tests/AliasVault.UnitTests/AliasVault.UnitTests.csproj
- apps/server/Tests/AliasVault.UnitTests/TestData/Exports/keepass_escaped_quotes.csv
- apps/server/Tests/AliasVault.UnitTests/TestData/Exports/keepass_special_chars.csv
- apps/server/Tests/AliasVault.UnitTests/Utilities/ImportExportTests.cs
- apps/server/Utilities/AliasVault.ImportExport/Importers/BaseImporter.cs
- apps/server/Utilities/AliasVault.ImportExport/Importers/BitwardenImporter.cs
- apps/server/Utilities/AliasVault.ImportExport/Importers/ChromeImporter.cs
- apps/server/Utilities/AliasVault.ImportExport/Importers/DashlaneImporter.cs
- apps/server/Utilities/AliasVault.ImportExport/Importers/DropboxImporter.cs
- apps/server/Utilities/AliasVault.ImportExport/Importers/FirefoxImporter.cs
- apps/server/Utilities/AliasVault.ImportExport/Importers/GenericCsvImporter.cs
- apps/server/Utilities/AliasVault.ImportExport/Importers/KeePassImporter.cs
- apps/server/Utilities/AliasVault.ImportExport/Importers/KeePassXcImporter.cs
- apps/server/Utilities/AliasVault.ImportExport/Importers/LastPassImporter.cs
- apps/server/Utilities/AliasVault.ImportExport/Importers/OnePasswordImporter.cs
- apps/server/Utilities/AliasVault.ImportExport/Importers/ProtonPassImporter.cs
- apps/server/Utilities/AliasVault.ImportExport/Importers/StrongboxImporter.cs
> CSV import does not handle special characters correctly in KeePass import

- .github/workflows/release.yml
- apps/server/AliasVault.Admin/Dockerfile
- apps/server/AliasVault.Api/Dockerfile
- apps/server/AliasVault.Client/Dockerfile
- apps/server/Databases/AliasServerDb/Dockerfile
- apps/server/Dockerfile
- apps/server/Services/AliasVault.SmtpService/Dockerfile
- apps/server/Services/AliasVault.TaskRunner/Dockerfile
- apps/server/Utilities/AliasVault.InstallCli/Dockerfile
- dockerfiles/all-in-one/Dockerfile
- docs/misc/release/publish-new-release/index.md
> Add opencontainers annotations to docker images on publish

- apps/server/Dockerfile
- apps/server/entrypoint.sh
> Add filewatcher to reverse-proxy container to auto reload when SSL cert is updated

- apps/mobile-app/app/(tabs)/credentials/add-edit.tsx
- apps/mobile-app/app/(tabs)/settings/_layout.tsx
- apps/mobile-app/app/(tabs)/settings/import-export.tsx
- apps/mobile-app/app/(tabs)/settings/index.tsx
- apps/mobile-app/app/(tabs)/settings/password-generator.tsx
- apps/mobile-app/components/form/AdvancedPasswordField.tsx
- apps/mobile-app/components/form/FormInputCopyToClipboard.tsx
- apps/mobile-app/hooks/useVaultMutate.ts
- apps/mobile-app/hooks/useVaultSync.ts
- apps/mobile-app/i18n/locales/en.json
- apps/server/AliasVault.Client/wwwroot/css/tailwind.css
> Make default password generator settings available in mobile app

- apps/server/AliasVault.Admin/Main/Pages/MainBase.cs
- apps/server/AliasVault.Client/Main/Pages/MainBase.cs
- apps/server/Shared/AliasVault.RazorComponents/Headings/Breadcrumb.razor
- apps/server/Shared/AliasVault.RazorComponents/Models/BreadcrumbItem.cs
> Breadcrumb path "home" occurs twice due to translations

- apps/server/AliasVault.Client/Main/Components/Credentials/CredentialsTable.razor
- apps/server/AliasVault.Client/Main/Models/CredentialSortOrder.cs
- apps/server/AliasVault.Client/Main/Pages/Credentials/Home.razor
- apps/server/AliasVault.Client/Resources/Pages/Main/Credentials/Home.en.resx
- apps/server/AliasVault.Client/Services/SettingsService.cs
> Add credentials alphabetical sort option to web app

- apps/server/AliasVault.Client/Main/Models/CredentialEdit.cs
- apps/server/Databases/AliasClientDb/AliasClientDbContext.cs
> DateTime parsing with certain culture / translation settings can crash the web app

- apps/browser-extension/src/entrypoints/popup/components/EmailDomainField.tsx
- apps/mobile-app/components/form/EmailDomainField.tsx
> Email domain field input clearing not working correctly in extension and mobile app

- install.sh
> Run automatic Docker image cleanup after build and update

- apps/mobile-app/android/app/build.gradle
- apps/mobile-app/android/app/src/main/java/net/aliasvault/app/nativevaultmanager/NativeVaultManager.kt
- apps/mobile-app/android/app/src/main/java/net/aliasvault/app/vaultstore/VaultStore.kt
- apps/mobile-app/ios/NativeVaultManager/RCTNativeVaultManager.mm
- apps/mobile-app/ios/NativeVaultManager/VaultManager.swift
- apps/mobile-app/ios/Podfile
- apps/mobile-app/ios/Podfile.lock
- apps/mobile-app/ios/VaultStoreKit/VaultStore+Crypto.swift
- apps/mobile-app/package-lock.json
- apps/mobile-app/package.json
- apps/mobile-app/specs/NativeVaultManager.ts
- apps/mobile-app/utils/EncryptionUtility.tsx
> Replace react native argon2id with native argon2id implementation for iOS and Android

- apps/browser-extension/src/entrypoints/background/PopupMessageHandler.ts
- apps/browser-extension/src/entrypoints/contentScript/Popup.ts
- apps/browser-extension/src/entrypoints/popup/pages/credentials/CredentialAddEdit.tsx
- apps/browser-extension/src/utils/serviceDetection/ServiceDetectionUtility.ts
> Prepopulate service title and URL based on current tab in browser extension

- apps/browser-extension/src/utils/formDetector/FormDetector.ts
- apps/browser-extension/src/utils/formDetector/FormFiller.ts
- apps/browser-extension/src/utils/formDetector/__tests__/FormDetector.generic.test.ts
- apps/browser-extension/src/utils/formDetector/__tests__/test-forms/nested-custom-elements-confirm.html
- apps/browser-extension/src/utils/formDetector/__tests__/test-forms/nested-custom-elements.html
- docs/misc/dev/browser-extensions.md
> Browser autofill inserts duplicate characters in password fields on some login forms

- apps/mobile-app/android/app/build.gradle
- apps/mobile-app/android/build.gradle
> Upgrade android app to be compatible with 16kb page size

- apps/browser-extension/src/entrypoints/contentScript/Filter.ts
- apps/browser-extension/src/entrypoints/contentScript/__tests__/Filter.test.ts
- apps/mobile-app/android/app/src/main/java/net/aliasvault/app/autofill/AutofillService.kt
- apps/mobile-app/android/app/src/main/java/net/aliasvault/app/autofill/utils/CredentialMatcher.kt
- apps/mobile-app/android/app/src/main/res/drawable/ic_search.xml
- apps/mobile-app/android/app/src/test/java/net/aliasvault/app/nativevaultmanager/AutofillTest.kt
- apps/mobile-app/ios/VaultUI/Utils/CredentialFilter.swift
- apps/mobile-app/ios/VaultUITests/CredentialFilterTests.swift
> Autofill sometimes shows too much irrelevant suggestions

- docs/installation/docker-compose/index.md
- docs/installation/docker-compose/troubleshooting.md
- docs/installation/script/index.md
- docs/misc/private-vs-public-email.md
> Update self-host installation docs with Admin WebSocket troubleshooting
